version: "3"
services:
  ubuntu:
    image: fuke0501/ubuntu
    build: ./images/ubuntu/
    container_name: ubuntu

  web:
    image: fuke0501/nginx
    build: ./images/nginx/
    container_name: web_nginx
    depends_on:
      - ubuntu
      - php-fpm
    volumes:
      - ./src:/src
      - ./images/nginx/logs:/var/log/nginx
      - ./images/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./images/nginx/conf/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    restart: always
    networks:
      vpcbr:
        ipv4_address: 192.168.20.2

  php-fpm:
    image: fuke0501/php-fpm
    build: ./images/php/
    container_name: web_php
    depends_on:
      - ubuntu
    volumes:
      - ./src:/src
      - ./images/php/conf/php.ini:/etc/php/7.2/fpm/php.ini
      - ./images/php/conf/www.conf:/etc/php/7.2/fpm/pool.d/www.conf
    ports:
      - "9000:9000"
    restart: always
    links:
      - mysql_db
      - redis-server
    networks:
      vpcbr:
        ipv4_address: 192.168.20.3
  mysql_db:
    image: fuke0501/mysql5.7
    build: ./images/mysql/
    container_name: web_mysql
    volumes:
      - ./images/mysql/data:/var/lib/mysql
      - ./images/mysql/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
      - ./images/mysql/conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - "3306:3306"
    restart: always
    depends_on:
      - ubuntu
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=laravel@2018
      - MYSQL_USER=phper
      - MYSQL_PASSWORD=2018@laravel
    networks:
      vpcbr:
        ipv4_address: 192.168.20.4

  redis-server:
    image: fuke0501/redis
    build: ./images/redis
    container_name: web_redis
    volumes:
      - ./images/redis/data:/data
      - ./images/redis/conf/redis.conf:/etc/redis/redis.conf
      - ./images/redis/log:/var/log/redis
    ports:
      - "6379:6379"
    restart: always
    depends_on:
      - ubuntu
    networks:
      vpcbr:
        ipv4_address: 192.168.20.5

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 192.168.20.0/24
