version: "2"
services:
  ubuntu:
    # image: fuke0501/ubuntu
    image: index.docker.io/fuke0501/ubuntu
    build: ./images/ubuntu/
    container_name: ubuntu

  web:
    image: index.docker.io/fuke0501/nginx
    # image: fuke0501/nginx
    build: ./images/nginx/
    container_name: web_nginx
    depends_on:
      - ubuntu
      - php-fpm
    volumes:
      - ./app:/app
      - ./images/nginx/logs:/var/log/nginx
      - ./images/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./images/nginx/conf/conf.d:/etc/nginx/conf.d
    ports:
      - "8080:80"
      - "4430:443"
    privileged: true
    restart: always
    networks:
      vpcbr:
        ipv4_address: 10.0.0.2

  php-fpm:
    image: index.docker.io/fuke0501/php-fpm
    # image: fuke0501/php-fpm
    build: ./images/php/
    container_name: web_php
    depends_on:
      - ubuntu
    volumes:
      - ./app:/app
      - ./images/php/conf/php.ini:/etc/php/7.0/fpm/php.ini
      - ./images/php/conf/www.conf:/etc/php/7.0/fpm/pool.d/www.conf
    ports:
      - "9000:9000"
    privileged: true
    restart: always
    links:
      - mysql_db
      - redis-server
    networks:
      vpcbr:
        ipv4_address: 10.0.0.3

  php-fpm-71:
    image: index.docker.io/fuke0501/php-fpm71
    # image: fuke0501/php-fpm71
    build: 
      context: ./images/php
      dockerfile: Dockerfile-php7.1
    container_name: web_php71
    depends_on:
      - ubuntu
    volumes:
      - ./app:/app
      - ./images/php/conf/php.ini:/etc/php/7.1/fpm/php.ini
      - ./images/php/conf/www.conf:/etc/php/7.1/fpm/pool.d/www.conf
    ports:
      - "19000:9000"
    privileged: true
    restart: always
    links:
      - mysql_db
      - redis-server
    networks:
      vpcbr:
        ipv4_address: 10.0.0.7

  php-fpm-ffmpeg:
    image: index.docker.io/fuke0501/php-fpmffmpeg
    # image: fuke0501/php-fpmffmpeg
    build: 
      context: ./images/php
      dockerfile: Dockerfile-ffmpeg
    container_name: web_phpffmpeg
    depends_on:
      - ubuntu
    volumes:
      - ./app:/app
      - ./images/php/conf/php.ini:/etc/php/7.1/fpm/php.ini
      - ./images/php/conf/www.conf:/etc/php/7.1/fpm/pool.d/www.conf
    ports:
      - "29000:9000"
    privileged: true
    restart: always
    links:
      - mysql_db
      - redis-server
    networks:
      vpcbr:
        ipv4_address: 10.0.0.8

  mysql_db:
    image: index.docker.io/fuke0501/mysql5.7
    # image: fuke0501/mysql5.7
    build: ./images/ubuntu-mysql/
    container_name: web_mysql
    volumes:
      - ./images/ubuntu-mysql/data:/var/lib/mysql
      - ./images/ubuntu-mysql/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    ports:
      - "3307:3306"
    privileged: true
    restart: always
    depends_on:
      - ubuntu
    environment:
      - MYSQL_USER_DB=laravel_db
      - MYSQL_ROOT_PWD=root
      - MYSQL_USER=laravel
      - MYSQL_USER_PWD=laravel
    networks:
      vpcbr:
        ipv4_address: 10.0.0.4

  redis-server:
    image: index.docker.io/fuke0501/redis
    # image: fuke0501/redis
    build: ./images/redis
    container_name: web_redis
    volumes:
      - ./images/redis/data:/data
      - ./images/redis/conf/redis.conf:/etc/redis/redis.conf
      - ./images/redis/log:/var/log/redis
    ports:
      - "16379:6379"
    privileged: true
    restart: always
    depends_on:
      - ubuntu
    networks:
      vpcbr:
        ipv4_address: 10.0.0.5

  official_mysql_db:
    image: index.docker.io/fuke0501/mysql5.7-official
    # image: fuke0501/mysql5.7-official
    build: ./images/mysql/
    container_name: web_mysql_official
    volumes:
      - ./images/mysql/data:/var/lib/mysql
      - ./images/mysql/conf/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
    ports:
      - "13060:3306"
    privileged: true
    restart: always
    environment:
      - MYSQL_DATABASE=laravel_db
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=laravel
    networks:
      vpcbr:
        ipv4_address: 10.0.0.6

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.0.0.0/16
         gateway: 10.0.0.1
